language: python

python:
  - "3.2"

# command to install dependencies
# - because we validate ourselves this is special
install:
  - pip install vvv --use-mirrors

# command to run tests
script: vvv ./src/www